version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - loose-funds
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    
  seq:
    image: datalust/seq:latest
    container_name: seq
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
    networks:
      - loose-funds
    ports:
      - "5341:80"
    volumes:
      - seq:/data

networks:
  loose-funds:
    name: loose-funds
    external: true

volumes:
  postgres:
  seq:


