version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - loose-funds
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  postgres-gui:
    image: dpage/pgadmin4:latest
    container_name: postgres-gui
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "2345:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=ad@min.ad
      - PGADMIN_DEFAULT_PASSWORD=password
    networks:
      - loose-funds
    volumes:
      - pg_admin:/var/lib/pgadmin

  seq:
    image: datalust/seq:latest
    container_name: seq
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
    networks:
      - loose-funds
    ports:
      - "5341:80"
    volumes:
      - seq:/data

  rabbit-mq:
    image: masstransit/rabbitmq
    container_name: rabbit-mq
    restart: unless-stopped
    networks:
      - loose-funds
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbit-mq:/var/lib/rabbitmq/
      - rabbit-mq:/var/log/rabbitmq/

networks:
  loose-funds:

volumes:
  postgres:
  seq:
  pg_admin:
  rabbit-mq:


